#### ndarry数组，多维性

In [2]:
import numpy as np
import matplotlib.pyplot as plt
list1=[12,323,4,5,6]
arr=np.array([[1,2,3,4,5],list1]) #array的参数是列表也可以使用dtype=np.数据类型
print(arr)
print(arr.ndim)   #数组维数
print(arr.size)   #总元素个数
print(arr.dtype)  #数组元素类型
print(arr.shape)  #数组的形状多维几行几列（行，列）一维（元素个数，）

[[  1   2   3   4   5]
 [ 12 323   4   5   6]]
2
10
int64
(2, 5)


In [33]:
arr1=np.array([[44,44,66],[66,66,66]])  #array使用相同长度的子列表行之间的元素必须相同个数
print(arr1)
arr2=np.copy(arr1)
print(arr2)         #复制数组copy()方法
print(arr1.ndim)
arr=np.array([1,'hello'])  #相同数据类型自动转换，大部分都是转换为字符串保证更多信息保留
print(arr)

['1' 'hello']


In [49]:
arr=np.zeros((2,2),dtype=int)  #预定义形状全0 后者全1矩阵
arr0=np.zeros_like(arr)        #模仿形状，自己定义数字填充
print(arr0)

arr1=np.ones((3,5),dtype=int)
arr2=np.ones_like(arr1)
print(arr1)

arr2=np.empty((3,5)) #未初始化的数组，随机数字
print(arr2)

arr3=np.full((3,4),2025)  #初始化指定值的矩阵full方法,用2025填充
arr4=np.full_like(arr3,2028)
print(arr4)

[[0 0]
 [0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[5.e-324 5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324 5.e-324]]
[[2028 2028 2028 2028]
 [2028 2028 2028 2028]
 [2028 2028 2028 2028]]


#### 等差数列

In [51]:
arr=np.arange(1,10,2) #参数为起点终点和步长
print(arr)
arr1=np.linspace(1,10,5) #起点终点和取的数字个数均匀间隔
print(arr1)

[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


#### 对数间隔数列

In [52]:
arr=np.logspace(0,4,3,base=2) #0~4是指数范围，3是个数，base是底，默认底数是10
print(arr)

[ 1.  4. 16.]


### 单位矩阵，对角矩阵

In [62]:
arr=np.eye(3,dtype=int)   #单位矩阵对角线都是1
arr1=np.diag([1,2,3,4])  #主对角线参数为对角线元素
arr2=np.random.randint(1,4,(3,4))  #生成1~4随机整数的数组
arr3=np.random.randn(2,2)        #随机数列的正态分布两边小中间大-3~3之间
print(f'单位阵:\n{arr}\n对角阵:\n{arr1}\n随机矩阵:\n{arr2}\n{arr3}\n')

单位阵:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
对角阵:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
随机矩阵:
[[3 3 2 3]
 [2 1 3 3]
 [2 3 2 3]]
[[-0.15956007 -2.24563383]
 [-0.09281993 -0.55403597]]



#### 一维数组的索引与切片

In [70]:
arr=np.random.randint(1,10,5)
arr1=np.random.randint(1,10,(3,4))
print(arr)
print(arr1)

[9 8 2 9 1]
[[6 3 2 2]
 [5 8 4 4]
 [5 4 1 1]]


In [72]:
print(arr[:]) # :默认打印全部的元素
print(arr[1:3])  #下标1到3之前的数字
print(arr1[1,2:4])  #参数1是第一行, 后面的参数是下标2到下标4之前
print(arr1[arr1>2])  #bool索引，返回的是一维数组

[9 8 2 9 1]
[8 2]
[4 4]
[6 3 5 8 4 4 5 4]


### 算术运算

In [3]:
a=np.array([1,2,3])  #ndarray的数组可以直接对应位置相加减乘除，python源生数组是连接数组
b=np.array([3,4,5])
print(a+b)
print(a-b)
print(a*b)
print(a+3)          #array与标量数字进行加减操作时候会对每个元素进行操作
c=[1,2,3]
d=[3,4,5]
print(c+d)         #加法连接列表，没有运算，只能通过循环进行对应位置相加减

[4 6 8]
[-2 -2 -2]
[ 3  8 15]
[4 5 6]
[1, 2, 3, 3, 4, 5]


##### 广播机制，同一纬度1 * 3和3 * 1的数组会扩成3*3，不满足维度行列相同不能进行广播

In [6]:
a=np.array([1,2,3])
b=np.array([[1],[2],[3]])
'''
广播机制的运算规则，a会被扩成
1 2 3
1 2 3
1 2 3
b会扩成
1 1 1
2 2 2
3 3 3
然后进行对应位置相加减
'''
print(a+b)
print(a*b)  #对应位置相乘
print(a @ b)   #矩阵乘法，取a行乘以b的每一列的到第一列的数字，矩阵位置(2,3)a的第二行乘以b的第三列

[[2 3 4]
 [3 4 5]
 [4 5 6]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
