### numpy的基本函数

In [2]:
import numpy as np
from scipy.special.cython_special import cosdg

# 平方根
print(np.sqrt(9))  #数字
print(np.sqrt([1,4,9]))  #列表
a=np.array([[1],[4],[9]])  #矩阵
print(np.sqrt(a))

3.0
[1. 2. 3.]
[[1.]
 [2.]
 [3.]]


In [3]:
# 计算e的指数
print(np.exp(1))  #e等于2.718281828459045

2.718281828459045


In [4]:
# 计算自然对数
print(np.log(1))  #log1等于0

0.0


In [8]:
# 计算三角函数
print(np.sin(np.pi/2)) #sin pi/2=1
print(np.cos(0))   #cos 0=-1

1.0
1.0


In [10]:
# 计算绝对值
a=np.array([[1,-2],[-3,4]])
print(np.abs(a))  #参数可以为矩阵全部取绝对值

[[1 2]
 [3 4]]


In [11]:
# 计算幂函数
a=[1,2,3]
print(np.power(a,2)) #参数的每一个位置都平方

[1 4 9]


In [13]:
# 四舍五入
print(np.round([3.2,4.5,2.7,8.9])) #4.5不会进位，严格大于五才会进位

[3. 4. 3. 9.]


In [26]:
# 向上取整，向下取整
a=np.array([3.2,4.5,2.7,10.9])
print(np.ceil(a))  #向上取整：去掉小数个位加一
print(np.floor(a)) #向下取整，去掉小数个位不变

[ 4.  5.  3. 11.]
[ 3.  4.  2. 10.]


In [2]:
import numpy as np
# 检测缺失值，np.nan缺失返回True，不确实返回False
np.isnan([1,2,np.nan])


array([False, False,  True])

### 统计函数
### 随机，求和，平均值，中位数，标准差，方差，最小最大值

In [3]:
a=np.random.randint(1,20,8)
print(a)

[10 19 14  6 12  7 13  9]


In [4]:
print(np.sum(a)) #求和np.sum()

90


In [13]:
print(np.mean(a)) #求平均值np.mean()
print(np.median(a))  #中位数排序后中间的数np.median()
#------------------------ 分位数就是在数轴上的位置
#10 19 14  6 12  7 13  9
print(np.percentile(a,25)) #分位数，（数组，前25%的比例）
#计算步骤：先排序
# 再位置公式：p×(n−1)+1 p是0.25称作分位点
# 区间比例乘以区间个数n-1，0.25*7+1=2.75
#2.75即第二个数和第三个数之间，并靠近第三个数
# 从第二个数开始向第三个数移动0.75的间距 7+0.75*(9-7)=7+1.5=8.5

11.25
11.0
8.5


In [7]:
# 方差(计算数据的离散程度)和标准差（方差开根号）
# 方差的计算公式：
# 1. 先求平均值
# 2. 再求每个数差平均值的平方相加最后除以个数等于方差
print(np.var(a))  # var方差
print(np.std(a))  # 标准差

15.4375
3.929058411375428


In [49]:
#最大最小值
print(a)
print(np.max(a),np.argmax(a)) #最值和索引argmax
print(np.min(a),np.argmin(a))
#矩阵的行列最大最小值只需要加上参数axis=0按列，axis=1按行
b=np.random.randint(1,20,size=(3,4))
print(b)
print(np.max(b,axis=1),np.argmax(b))
print(np.min(b,axis=0),np.argmin(b))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
12 11
1 0
[[ 6 13  8  3]
 [14  5 17 16]
 [ 8  8 17  2]]
[13 17 17] 6
[6 5 8 2] 11


In [14]:
# 累计和，累积积
print(np.cumsum([1,2,4]))
print(np.cumprod([1,2,4])) #第一个位置等于本身，第二个位置等于前两项相称...

[1 3 7]
[1 2 8]


### 比较函数

In [16]:
print(np.greater([1,2,3,4,5],3))  #逐个进行比较比3大的返回True
print(np.less([1,2,3,4,5],3))       #逐个进行比3小的返回True
print(np.equal([1,2,3,4,5],[1,2,3,4,5])) #两个比较对象必须相同长度

[False False False  True  True]
[ True  True False False False]
[ True  True  True  True  True]


In [20]:
print(np.logical_and([1,0],[1,1])) #逐个相同位置比较两个不是0才是True
print(np.logical_or([1,0],[1,1]))  #有1就是True
print(np.logical_not([1,0])) # 取反1为False，2为True
print(np.any([1,1,0]))   # 有一个1是True
print(np.all([1,0,0]))   # 全部大于0才是True

[ True False]
[ True  True]
[False  True]
True
False


In [32]:
# 自定义条件 np.where(条件，符合条件，不符合条件)
arr=np.array([1,2,3,4,5,6])
print(np.where(arr>3,arr,1))
print(np.where(arr>3,1,0))  #可以进行1和0快速分化
#where还可以进行嵌套
print(np.where(arr>3,'大',np.where(
    arr<5,'刚好','不行'
    )
))
# np.select([条件]，[返回值])
score=np.random.randint(1,20,10)
print(score)
print(np.select([score>2,score<2],['优秀','不及格'],default='未知'))

[1 1 1 4 5 6]
[0 0 0 1 1 1]
['刚好' '刚好' '刚好' '大' '大' '大']
[19  8 17  3  7  6 14  1  4  3]
['优秀' '优秀' '优秀' '优秀' '优秀' '优秀' '优秀' '不及格' '优秀' '优秀']


### 排序函数

In [48]:
#排序函数sort()和np.sort()的区别
arr=np.array([1,7,9,0,0,5,6])
print(np.sort(arr)) #np.sort()不改变原数组的值
print(np.sort(arr)[::-1])  #倒序加上切片操作就行
print(np.argsort(arr)) #返回排序的下标
print(arr)
arr.sort()  #改变原始数组
print(arr)

#去重函数np.unique内部先排序的再去重
print(np.unique(arr))

#ndarry的加法不是拼接是对应位置相加,concatenate(arr1,arr2)才是拼接
arr1=np.array([1,2,43,5,6])
arr2=np.array([1,43,5,7,9])
print(arr1+arr2)
print(np.concatenate((arr1,arr2)))
# 数组的分割
print(np.split(arr1,[1,2,3])) #后面参数是指定位置，或者整除

[0 0 1 5 6 7 9]
[9 7 6 5 1 0 0]
[3 4 0 5 6 1 2]
[1 7 9 0 0 5 6]
[0 0 1 5 6 7 9]
[0 1 5 6 7 9]
[ 2 45 48 12 15]
[ 1  2 43  5  6  1 43  5  7  9]
[array([1]), array([2]), array([43]), array([5, 6])]


#### numpy的使用案例

In [27]:
"""
    温度数据分析，一周的最高温度为[28,30,29,31,32,30,29]
    -找出平均气温，最高气温，最低气温
    -找出气温超过30°的天气
"""
import numpy as np
tem=np.array([28,30,29,31,32,30,29])
print('%.3f'%np.mean(tem))  #平均值函数np.mean()
print(np.max(tem))
print(np.min(tem))

i=0
sum=0
while i<7:
    if tem[i]>30:
        print(f"第{i+1}天气温超过30°C")
        sum+=1
    i+=1
print(f"气温超过30°c的天数为：{sum}天")




29.857
32
28
第4天气温超过30°C
第5天气温超过30°C
气温超过30°c的天数为：2天


In [36]:
"""
    -计算成绩的平均分中位数和标准差
    -将成绩转换为百分制
"""
score=np.array([85,90,78,92,88])
print(np.sort(score))
print(np.mean(score))
print(np.median(score))
print("%.3f"%np.std(score))
for x in score:
    print(f"十分制{x/10}%")

[78 85 88 90 92]
86.6
88.0
4.883
十分制8.5%
十分制9.0%
十分制7.8%
十分制9.2%
十分制8.8%


In [67]:
"""
    矩阵运算，计算给定矩阵
    A=[[1,2],[3,4]],B=[[5,6],[7,8]]
    计算A+B,A*B
    计算A和B的矩阵乘法
"""
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A+B)
print(A*B)
print(A @ B) #行乘以列
C=np.concatenate([A,B]) #拼接矩阵
print(C)
np.reshape(C,(2,4))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
"""
生成一个（3，4）的随机数组，范围【0,10】
-计算每列的最大值和每行的最小值
-将数组中的所有奇数替换为-1
"""
a=np.random.randint(0,10,(3,4)) #左闭右开不包含右边
print(a)
print(f"每列的最大值{np.max(a,axis=0)}") #列数是0
print(f"每行的最小值{np.min(a,axis=1)}") #行数是1
print(np.where(a%2==1,-1,a))  #利用where生成新的数组
a[a%2==1]=-1  #利用布尔值进行原数组上的修改
print(a)

[[1 8 4 0]
 [1 4 9 4]
 [0 6 4 7]]
每列的最大值[1 8 9 7]
每行的最小值[0 1 0]
[[-1  8  4  0]
 [-1  4 -1  4]
 [ 0  6  4 -1]]
[[-1  8  4  0]
 [-1  4 -1  4]
 [ 0  6  4 -1]]


In [62]:
"""
数组变形
创建1到12的一维数组，并转换为（3，4）的二维数组
-计算每行的和每列的平均值
-将数组转化为一维数组
"""
a=np.arange(1,13)
b=a.reshape(3,4)  #reshape转换数组
print(a)
print(b)
print(f"每行的和{np.sum(b,axis=1)}")
print(f"每列的平均值{np.mean(b,axis=0)}")
c=b.reshape(12)
print(c)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和[10 26 42]
每列的平均值[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [71]:
"""
    唯一值和排序
    给定数组[2,1,2,3,1,4,3]
    -找出数组中的唯一值并排序
    -计算每个唯一值出现的次数
"""
a=np.array([2,1,2,3,1,4,3])
uni_q,counts=np.unique(a,return_counts=True) #返回出现次数，点击函数查看参数
print(uni_q)
print(counts)

[1 2 3 4]
[2 2 2 1]
[1 0 3 5]
